#!/usr/bin/env ruby

require 'find'

def ifdef path
	path.gsub('/', '__').gsub('.', '_').upcase
end

def check file
	skip = %w[
		haruhi/config/all.h
		haruhi/config/system.h
		haruhi/config/version.h
		haruhi/utility/confusion.h
	]
	return true if skip.include?(file)
	File.open(file).readlines.any? { |line| line.chomp == "\#include <haruhi/config/all.h>" }
end

def find dir
	Find.find(dir) do |path|
		if File.directory? path
			if path == '.'
				Find.prune
			else
				next
			end
		else
			begin
				if path.end_with?('.h') && !check(path)
					puts "../src/#{path}"
				end
			rescue => e
				puts "Could not check file #{file}: #{e.message}"
			end
		end
	end
end

Dir.chdir '../src'
find 'haruhi'
