# vim:ts=4

######## /lib/si ########

SI_HEADERS += lib/si/all.h
SI_HEADERS += lib/si/acceleration.h
SI_HEADERS += lib/si/angle.h
SI_HEADERS += lib/si/area.h
SI_HEADERS += lib/si/capacity.h
SI_HEADERS += lib/si/current.h
SI_HEADERS += lib/si/density.h
SI_HEADERS += lib/si/force.h
SI_HEADERS += lib/si/constants.h
SI_HEADERS += lib/si/frequency.h
SI_HEADERS += lib/si/length.h
SI_HEADERS += lib/si/lonlat.h
SI_HEADERS += lib/si/operators.h
SI_HEADERS += lib/si/pressure.h
SI_HEADERS += lib/si/speed.h
SI_HEADERS += lib/si/temperature.h
SI_HEADERS += lib/si/time.h
SI_HEADERS += lib/si/torque.h
SI_HEADERS += lib/si/volume.h
SI_HEADERS += lib/si/weight.h
SI_HEADERS += lib/si/value.h

SI_SOURCES += lib/si/acceleration.cc
SI_SOURCES += lib/si/angle.cc
SI_SOURCES += lib/si/area.cc
SI_SOURCES += lib/si/capacity.cc
SI_SOURCES += lib/si/current.cc
SI_SOURCES += lib/si/density.cc
SI_SOURCES += lib/si/force.cc
SI_SOURCES += lib/si/frequency.cc
SI_SOURCES += lib/si/length.cc
SI_SOURCES += lib/si/lonlat.cc
SI_SOURCES += lib/si/pressure.cc
SI_SOURCES += lib/si/speed.cc
SI_SOURCES += lib/si/temperature.cc
SI_SOURCES += lib/si/time.cc
SI_SOURCES += lib/si/torque.cc
SI_SOURCES += lib/si/volume.cc
SI_SOURCES += lib/si/weight.cc

SRC_HEADERS += $(SI_HEADERS)
SRC_SOURCES += $(SI_SOURCES)

######## /application ########

SRC_HEADERS += haruhi/application/fail.h
SRC_HEADERS += haruhi/application/haruhi.h
SRC_HEADERS += haruhi/application/services.h

SRC_SOURCES += haruhi/application/fail.cc
SRC_SOURCES += haruhi/application/haruhi.cc
SRC_SOURCES += haruhi/application/main.cc
SRC_SOURCES += haruhi/application/services.cc

SRC_MOCHDRS += haruhi/application/haruhi.h
SRC_MOCHDRS += haruhi/application/services.h

######## /components/audio_backend/transports ########

SRC_HEADERS += haruhi/components/audio_backend/transports/jack_transport.h

SRC_SOURCES += haruhi/components/audio_backend/transports/jack_transport.cc

######## /components/audio_backend ########

SRC_HEADERS += haruhi/components/audio_backend/backend.h
SRC_HEADERS += haruhi/components/audio_backend/exception.h
SRC_HEADERS += haruhi/components/audio_backend/input_dialog.h
SRC_HEADERS += haruhi/components/audio_backend/input_item.h
SRC_HEADERS += haruhi/components/audio_backend/output_dialog.h
SRC_HEADERS += haruhi/components/audio_backend/output_item.h
SRC_HEADERS += haruhi/components/audio_backend/port_dialog.h
SRC_HEADERS += haruhi/components/audio_backend/port_item.h
SRC_HEADERS += haruhi/components/audio_backend/tree.h
SRC_HEADERS += haruhi/components/audio_backend/transport.h

SRC_SOURCES += haruhi/components/audio_backend/backend.cc
SRC_SOURCES += haruhi/components/audio_backend/input_dialog.cc
SRC_SOURCES += haruhi/components/audio_backend/input_item.cc
SRC_SOURCES += haruhi/components/audio_backend/output_dialog.cc
SRC_SOURCES += haruhi/components/audio_backend/output_item.cc
SRC_SOURCES += haruhi/components/audio_backend/port_dialog.cc
SRC_SOURCES += haruhi/components/audio_backend/port_item.cc
SRC_SOURCES += haruhi/components/audio_backend/tree.cc

SRC_MOCHDRS += haruhi/components/audio_backend/backend.h
SRC_MOCHDRS += haruhi/components/audio_backend/input_dialog.h
SRC_MOCHDRS += haruhi/components/audio_backend/output_dialog.h

######## /components/event_backend/transports ########

SRC_HEADERS += haruhi/components/event_backend/transports/alsa_transport.h

SRC_SOURCES += haruhi/components/event_backend/transports/alsa_transport.cc

######## /components/event_backend ########

SRC_HEADERS += haruhi/components/event_backend/backend.h
SRC_HEADERS += haruhi/components/event_backend/controller_with_port_dialog.h
SRC_HEADERS += haruhi/components/event_backend/controller_with_port_item.h
SRC_HEADERS += haruhi/components/event_backend/device_with_port_dialog.h
SRC_HEADERS += haruhi/components/event_backend/device_with_port_item.h
SRC_HEADERS += haruhi/components/event_backend/tree.h
SRC_HEADERS += haruhi/components/event_backend/port_item.h
SRC_HEADERS += haruhi/components/event_backend/transport.h

SRC_SOURCES += haruhi/components/event_backend/backend.cc
SRC_SOURCES += haruhi/components/event_backend/controller_with_port_dialog.cc
SRC_SOURCES += haruhi/components/event_backend/controller_with_port_item.cc
SRC_SOURCES += haruhi/components/event_backend/device_with_port_dialog.cc
SRC_SOURCES += haruhi/components/event_backend/device_with_port_item.cc
SRC_SOURCES += haruhi/components/event_backend/tree.cc
SRC_SOURCES += haruhi/components/event_backend/port_item.cc

SRC_MOCHDRS += haruhi/components/event_backend/backend.h

######## /components/devices_manager ########

SRC_HEADERS += haruhi/components/devices_manager/controller.h
SRC_HEADERS += haruhi/components/devices_manager/controller_dialog.h
SRC_HEADERS += haruhi/components/devices_manager/controller_item.h
SRC_HEADERS += haruhi/components/devices_manager/device.h
SRC_HEADERS += haruhi/components/devices_manager/device_dialog.h
SRC_HEADERS += haruhi/components/devices_manager/device_item.h
SRC_HEADERS += haruhi/components/devices_manager/item.h
SRC_HEADERS += haruhi/components/devices_manager/model.h
SRC_HEADERS += haruhi/components/devices_manager/panel.h
SRC_HEADERS += haruhi/components/devices_manager/settings.h
SRC_HEADERS += haruhi/components/devices_manager/tree.h

SRC_SOURCES += haruhi/components/devices_manager/controller.cc
SRC_SOURCES += haruhi/components/devices_manager/controller_dialog.cc
SRC_SOURCES += haruhi/components/devices_manager/controller_item.cc
SRC_SOURCES += haruhi/components/devices_manager/device.cc
SRC_SOURCES += haruhi/components/devices_manager/device_dialog.cc
SRC_SOURCES += haruhi/components/devices_manager/device_item.cc
SRC_SOURCES += haruhi/components/devices_manager/item.cc
SRC_SOURCES += haruhi/components/devices_manager/model.cc
SRC_SOURCES += haruhi/components/devices_manager/panel.cc
SRC_SOURCES += haruhi/components/devices_manager/settings.cc
SRC_SOURCES += haruhi/components/devices_manager/tree.cc

SRC_MOCHDRS += haruhi/components/devices_manager/controller_dialog.h
SRC_MOCHDRS += haruhi/components/devices_manager/device_dialog.h
SRC_MOCHDRS += haruhi/components/devices_manager/panel.h
SRC_MOCHDRS += haruhi/components/devices_manager/tree.h

######## /components/ports_connector ########

SRC_HEADERS += haruhi/components/ports_connector/panel.h
SRC_HEADERS += haruhi/components/ports_connector/ports_connector.h
SRC_HEADERS += haruhi/components/ports_connector/connector.h
SRC_HEADERS += haruhi/components/ports_connector/ports_list.h
SRC_HEADERS += haruhi/components/ports_connector/comparable_item.h
SRC_HEADERS += haruhi/components/ports_connector/highlightable_item.h
SRC_HEADERS += haruhi/components/ports_connector/group_item.h
SRC_HEADERS += haruhi/components/ports_connector/port_item.h
SRC_HEADERS += haruhi/components/ports_connector/unit_item.h
SRC_HEADERS += haruhi/components/ports_connector/units_combobox.h

SRC_SOURCES += haruhi/components/ports_connector/panel.cc
SRC_SOURCES += haruhi/components/ports_connector/ports_connector.cc
SRC_SOURCES += haruhi/components/ports_connector/connector.cc
SRC_SOURCES += haruhi/components/ports_connector/ports_list.cc
SRC_SOURCES += haruhi/components/ports_connector/comparable_item.cc
SRC_SOURCES += haruhi/components/ports_connector/highlightable_item.cc
SRC_SOURCES += haruhi/components/ports_connector/group_item.cc
SRC_SOURCES += haruhi/components/ports_connector/port_item.cc
SRC_SOURCES += haruhi/components/ports_connector/unit_item.cc
SRC_SOURCES += haruhi/components/ports_connector/units_combobox.cc

SRC_MOCHDRS += haruhi/components/ports_connector/panel.h
SRC_MOCHDRS += haruhi/components/ports_connector/ports_connector.h
SRC_MOCHDRS += haruhi/components/ports_connector/ports_list.h

######## /components/presets_manager ########

SRC_HEADERS += haruhi/components/presets_manager/category.h
SRC_HEADERS += haruhi/components/presets_manager/category_item.h
SRC_HEADERS += haruhi/components/presets_manager/helpers.h
SRC_HEADERS += haruhi/components/presets_manager/model.h
SRC_HEADERS += haruhi/components/presets_manager/package.h
SRC_HEADERS += haruhi/components/presets_manager/package_item.h
SRC_HEADERS += haruhi/components/presets_manager/preset.h
SRC_HEADERS += haruhi/components/presets_manager/preset_editor.h
SRC_HEADERS += haruhi/components/presets_manager/preset_item.h
SRC_HEADERS += haruhi/components/presets_manager/presets_tree.h
SRC_HEADERS += haruhi/components/presets_manager/presets_manager.h

SRC_SOURCES += haruhi/components/presets_manager/category.cc
SRC_SOURCES += haruhi/components/presets_manager/category_item.cc
SRC_SOURCES += haruhi/components/presets_manager/helpers.cc
SRC_SOURCES += haruhi/components/presets_manager/model.cc
SRC_SOURCES += haruhi/components/presets_manager/package.cc
SRC_SOURCES += haruhi/components/presets_manager/package_item.cc
SRC_SOURCES += haruhi/components/presets_manager/preset.cc
SRC_SOURCES += haruhi/components/presets_manager/preset_editor.cc
SRC_SOURCES += haruhi/components/presets_manager/preset_item.cc
SRC_SOURCES += haruhi/components/presets_manager/presets_tree.cc
SRC_SOURCES += haruhi/components/presets_manager/presets_manager.cc

SRC_MOCHDRS += haruhi/components/presets_manager/preset_editor.h
SRC_MOCHDRS += haruhi/components/presets_manager/presets_tree.h
SRC_MOCHDRS += haruhi/components/presets_manager/presets_manager.h

######## /config ########

SRC_HEADERS += haruhi/config/all.h
SRC_HEADERS += haruhi/config/resources.h
SRC_HEADERS += haruhi/config/system.h
SRC_HEADERS += haruhi/config/types.h

SRC_SOURCES += haruhi/config/resources.cc

NODEP_SOURCES += $(VERSION_FILE)

######## /dsp ########

SRC_HEADERS += haruhi/dsp/adsr.h
SRC_HEADERS += haruhi/dsp/delay_line.h
SRC_HEADERS += haruhi/dsp/envelope.h
SRC_HEADERS += haruhi/dsp/fft.h
SRC_HEADERS += haruhi/dsp/fft_filler.h
SRC_HEADERS += haruhi/dsp/filter.h
SRC_HEADERS += haruhi/dsp/functions.h
SRC_HEADERS += haruhi/dsp/harmonics_wave.h
SRC_HEADERS += haruhi/dsp/impulse_response.h
SRC_HEADERS += haruhi/dsp/modulated_wave.h
SRC_HEADERS += haruhi/dsp/noise.h
SRC_HEADERS += haruhi/dsp/one_pole_smoother.h
SRC_HEADERS += haruhi/dsp/parametric_wave.h
SRC_HEADERS += haruhi/dsp/ramp_smoother.h
SRC_HEADERS += haruhi/dsp/scaled_wave.h
SRC_HEADERS += haruhi/dsp/translated_wave.h
SRC_HEADERS += haruhi/dsp/wavetable.h
SRC_HEADERS += haruhi/dsp/wave.h
SRC_HEADERS += haruhi/dsp/utility.h

SRC_SOURCES += haruhi/dsp/adsr.cc
SRC_SOURCES += haruhi/dsp/delay_line.cc
SRC_SOURCES += haruhi/dsp/envelope.cc
SRC_SOURCES += haruhi/dsp/fft.cc
SRC_SOURCES += haruhi/dsp/fft_filler.cc
SRC_SOURCES += haruhi/dsp/noise.cc
SRC_SOURCES += haruhi/dsp/ramp_smoother.cc
SRC_SOURCES += haruhi/dsp/wavetable.cc
SRC_SOURCES += haruhi/dsp/wave.cc

######## /graph ########

SRC_HEADERS += haruhi/graph/audio_backend.h
SRC_HEADERS += haruhi/graph/audio_buffer.h
SRC_HEADERS += haruhi/graph/audio_port.h
SRC_HEADERS += haruhi/graph/backend.h
SRC_HEADERS += haruhi/graph/buffer.h
SRC_HEADERS += haruhi/graph/conn_set.h
SRC_HEADERS += haruhi/graph/event.h
SRC_HEADERS += haruhi/graph/event_backend.h
SRC_HEADERS += haruhi/graph/event_buffer.h
SRC_HEADERS += haruhi/graph/event_port.h
SRC_HEADERS += haruhi/graph/exception.h
SRC_HEADERS += haruhi/graph/graph.h
SRC_HEADERS += haruhi/graph/notification.h
SRC_HEADERS += haruhi/graph/port.h
SRC_HEADERS += haruhi/graph/ports.h
SRC_HEADERS += haruhi/graph/port_group.h
SRC_HEADERS += haruhi/graph/predicates.h
SRC_HEADERS += haruhi/graph/unit.h

SRC_SOURCES += haruhi/graph/audio_backend.cc
SRC_SOURCES += haruhi/graph/audio_buffer.cc
SRC_SOURCES += haruhi/graph/audio_port.cc
SRC_SOURCES += haruhi/graph/backend.cc
SRC_SOURCES += haruhi/graph/conn_set.cc
SRC_SOURCES += haruhi/graph/event.cc
SRC_SOURCES += haruhi/graph/event_backend.cc
SRC_SOURCES += haruhi/graph/event_buffer.cc
SRC_SOURCES += haruhi/graph/event_port.cc
SRC_SOURCES += haruhi/graph/graph.cc
SRC_SOURCES += haruhi/graph/notification.cc
SRC_SOURCES += haruhi/graph/port.cc
SRC_SOURCES += haruhi/graph/port_group.cc
SRC_SOURCES += haruhi/graph/unit.cc

######## /lib ########

SRC_HEADERS += haruhi/lib/controller.h
SRC_HEADERS += haruhi/lib/controller_param.h
SRC_HEADERS += haruhi/lib/controller_proxy.h
SRC_HEADERS += haruhi/lib/midi.h
SRC_HEADERS += haruhi/lib/param.h

SRC_SOURCES += haruhi/lib/controller.cc
SRC_SOURCES += haruhi/lib/controller_param.cc
SRC_SOURCES += haruhi/lib/controller_proxy.cc
SRC_SOURCES += haruhi/lib/midi.cc

######## /plugin ########

SRC_HEADERS += haruhi/plugin/has_presets.h
SRC_HEADERS += haruhi/plugin/plugin.h
SRC_HEADERS += haruhi/plugin/plugin_factory.h
SRC_HEADERS += haruhi/plugin/plugin_loader.h
SRC_HEADERS += haruhi/plugin/saveable_params.h

SRC_SOURCES += haruhi/plugin/plugin.cc
SRC_SOURCES += haruhi/plugin/plugin_factory.cc
SRC_SOURCES += haruhi/plugin/plugin_loader.cc

######## /session ########

SRC_HEADERS += haruhi/session/engine.h
SRC_HEADERS += haruhi/session/patch.h
SRC_HEADERS += haruhi/session/periodic_updater.h
SRC_HEADERS += haruhi/session/program.h
SRC_HEADERS += haruhi/session/session.h
SRC_HEADERS += haruhi/session/session_loader.h
SRC_HEADERS += haruhi/session/unit_bay.h

SRC_SOURCES += haruhi/session/engine.cc
SRC_SOURCES += haruhi/session/patch.cc
SRC_SOURCES += haruhi/session/periodic_updater.cc
SRC_SOURCES += haruhi/session/program.cc
SRC_SOURCES += haruhi/session/session.cc
SRC_SOURCES += haruhi/session/session_loader.cc
SRC_SOURCES += haruhi/session/unit_bay.cc

SRC_MOCHDRS += haruhi/session/patch.h
SRC_MOCHDRS += haruhi/session/periodic_updater.h
SRC_MOCHDRS += haruhi/session/session.h
SRC_MOCHDRS += haruhi/session/session_loader.h

######## /settings ########

SRC_HEADERS += haruhi/settings/settings.h
SRC_HEADERS += haruhi/settings/plugin_settings.h
SRC_HEADERS += haruhi/settings/haruhi_settings.h
SRC_HEADERS += haruhi/settings/has_presets_settings.h
SRC_HEADERS += haruhi/settings/session_loader_settings.h

SRC_SOURCES += haruhi/settings/settings.cc
SRC_SOURCES += haruhi/settings/plugin_settings.cc
SRC_SOURCES += haruhi/settings/haruhi_settings.cc
SRC_SOURCES += haruhi/settings/has_presets_settings.cc
SRC_SOURCES += haruhi/settings/session_loader_settings.cc

######## /utility ########

SRC_HEADERS += haruhi/utility/amplitude.h
SRC_HEADERS += haruhi/utility/atomic.h
SRC_HEADERS += haruhi/utility/backtrace.h
SRC_HEADERS += haruhi/utility/condition.h
SRC_HEADERS += haruhi/utility/confusion.h
SRC_HEADERS += haruhi/utility/decibels.h
SRC_HEADERS += haruhi/utility/exception.h
SRC_HEADERS += haruhi/utility/fast_pow.h
SRC_HEADERS += haruhi/utility/filesystem.h
SRC_HEADERS += haruhi/utility/frequency.h
SRC_HEADERS += haruhi/utility/hertz.h
SRC_HEADERS += haruhi/utility/id_allocator.h
SRC_HEADERS += haruhi/utility/lexical_cast.h
SRC_HEADERS += haruhi/utility/literals.h
SRC_HEADERS += haruhi/utility/lookup_pow.h
SRC_HEADERS += haruhi/utility/memory.h
SRC_HEADERS += haruhi/utility/mutex.h
SRC_HEADERS += haruhi/utility/noncopyable.h
SRC_HEADERS += haruhi/utility/normalized_frequency.h
SRC_HEADERS += haruhi/utility/numeric.h
SRC_HEADERS += haruhi/utility/pool_allocator.h
SRC_HEADERS += haruhi/utility/predicates.h
SRC_HEADERS += haruhi/utility/qdom.h
SRC_HEADERS += haruhi/utility/ref_counted.h
SRC_HEADERS += haruhi/utility/saveable_state.h
SRC_HEADERS += haruhi/utility/seconds.h
SRC_HEADERS += haruhi/utility/semaphore.h
SRC_HEADERS += haruhi/utility/simd_ops.h
SRC_HEADERS += haruhi/utility/shared.h
SRC_HEADERS += haruhi/utility/signal.h
SRC_HEADERS += haruhi/utility/sse_pow.h
SRC_HEADERS += haruhi/utility/thread.h
SRC_HEADERS += haruhi/utility/timing.h
SRC_HEADERS += haruhi/utility/units.h
SRC_HEADERS += haruhi/utility/work_performer.h

SRC_SOURCES += haruhi/utility/backtrace.cc
SRC_SOURCES += haruhi/utility/condition.cc
SRC_SOURCES += haruhi/utility/filesystem.cc
SRC_SOURCES += haruhi/utility/id_allocator.cc
SRC_SOURCES += haruhi/utility/lookup_pow.cc
SRC_SOURCES += haruhi/utility/mutex.cc
SRC_SOURCES += haruhi/utility/semaphore.cc
SRC_SOURCES += haruhi/utility/sse_pow.cc
SRC_SOURCES += haruhi/utility/thread.cc
SRC_SOURCES += haruhi/utility/work_performer.cc

######### /widgets ########

SRC_HEADERS += haruhi/widgets/clickable_label.h
SRC_HEADERS += haruhi/widgets/dial_control.h
SRC_HEADERS += haruhi/widgets/envelope_plot.h
SRC_HEADERS += haruhi/widgets/frequency_response_plot.h
SRC_HEADERS += haruhi/widgets/generic_item.h
SRC_HEADERS += haruhi/widgets/knob.h
SRC_HEADERS += haruhi/widgets/level_meter.h
SRC_HEADERS += haruhi/widgets/plot_frame.h
SRC_HEADERS += haruhi/widgets/styled_background.h
SRC_HEADERS += haruhi/widgets/texture_widget.h
SRC_HEADERS += haruhi/widgets/wave_plot.h

SRC_SOURCES += haruhi/widgets/clickable_label.cc
SRC_SOURCES += haruhi/widgets/dial_control.cc
SRC_SOURCES += haruhi/widgets/envelope_plot.cc
SRC_SOURCES += haruhi/widgets/frequency_response_plot.cc
SRC_SOURCES += haruhi/widgets/generic_item.cc
SRC_SOURCES += haruhi/widgets/knob.cc
SRC_SOURCES += haruhi/widgets/level_meter.cc
SRC_SOURCES += haruhi/widgets/plot_frame.cc
SRC_SOURCES += haruhi/widgets/styled_background.cc
SRC_SOURCES += haruhi/widgets/texture_widget.cc
SRC_SOURCES += haruhi/widgets/wave_plot.cc

SRC_MOCHDRS += haruhi/widgets/clickable_label.h
SRC_MOCHDRS += haruhi/widgets/dial_control.h
SRC_MOCHDRS += haruhi/widgets/envelope_plot.h
SRC_MOCHDRS += haruhi/widgets/frequency_response_plot.h
SRC_MOCHDRS += haruhi/widgets/knob.h
SRC_MOCHDRS += haruhi/widgets/level_meter.h

######### /plugins/yuki ########

SRC_HEADERS += plugins/yuki/dual_filter.h
SRC_HEADERS += plugins/yuki/filter_ir.h
SRC_HEADERS += plugins/yuki/filter_widget.h
SRC_HEADERS += plugins/yuki/has_id.h
SRC_HEADERS += plugins/yuki/has_widget.h
SRC_HEADERS += plugins/yuki/operator_widget.h
SRC_HEADERS += plugins/yuki/params.h
SRC_HEADERS += plugins/yuki/part.h
SRC_HEADERS += plugins/yuki/part_harmonics_widget.h
SRC_HEADERS += plugins/yuki/part_modulator_widget.h
SRC_HEADERS += plugins/yuki/part_oscillator_widget.h
SRC_HEADERS += plugins/yuki/part_manager.h
SRC_HEADERS += plugins/yuki/part_manager_widget.h
SRC_HEADERS += plugins/yuki/part_widget.h
SRC_HEADERS += plugins/yuki/plugin.h
SRC_HEADERS += plugins/yuki/voice.h
SRC_HEADERS += plugins/yuki/voice_manager.h
SRC_HEADERS += plugins/yuki/voice_modulator.h
SRC_HEADERS += plugins/yuki/voice_operator.h
SRC_HEADERS += plugins/yuki/voice_oscillator.h
SRC_HEADERS += plugins/yuki/yuki.h

SRC_SOURCES += plugins/yuki/dual_filter.cc
SRC_SOURCES += plugins/yuki/filter_ir.cc
SRC_SOURCES += plugins/yuki/filter_widget.cc
SRC_SOURCES += plugins/yuki/operator_widget.cc
SRC_SOURCES += plugins/yuki/params.cc
SRC_SOURCES += plugins/yuki/part.cc
SRC_SOURCES += plugins/yuki/part_harmonics_widget.cc
SRC_SOURCES += plugins/yuki/part_modulator_widget.cc
SRC_SOURCES += plugins/yuki/part_oscillator_widget.cc
SRC_SOURCES += plugins/yuki/part_manager.cc
SRC_SOURCES += plugins/yuki/part_manager_widget.cc
SRC_SOURCES += plugins/yuki/part_widget.cc
SRC_SOURCES += plugins/yuki/plugin.cc
SRC_SOURCES += plugins/yuki/voice.cc
SRC_SOURCES += plugins/yuki/voice_manager.cc
SRC_SOURCES += plugins/yuki/voice_modulator.cc
SRC_SOURCES += plugins/yuki/voice_operator.cc
SRC_SOURCES += plugins/yuki/voice_oscillator.cc
SRC_SOURCES += plugins/yuki/yuki.cc

SRC_MOCHDRS += plugins/yuki/filter_widget.h
SRC_MOCHDRS += plugins/yuki/operator_widget.h
SRC_MOCHDRS += plugins/yuki/plugin.h
SRC_MOCHDRS += plugins/yuki/part_harmonics_widget.h
SRC_MOCHDRS += plugins/yuki/part_modulator_widget.h
SRC_MOCHDRS += plugins/yuki/part_oscillator_widget.h
SRC_MOCHDRS += plugins/yuki/part_widget.h
SRC_MOCHDRS += plugins/yuki/part_manager_widget.h

######### /plugins/bugfuzzer ########

SRC_HEADERS += plugins/bugfuzzer/bugfuzzer.h

SRC_SOURCES += plugins/bugfuzzer/bugfuzzer.cc

SRC_MOCHDRS += plugins/bugfuzzer/bugfuzzer.h

######### /plugins/eg ########

SRC_HEADERS += plugins/eg/eg.h
SRC_HEADERS += plugins/eg/key_manager.h
SRC_HEADERS += plugins/eg/params.h
SRC_HEADERS += plugins/eg/plugin.h

SRC_SOURCES += plugins/eg/eg.cc
SRC_SOURCES += plugins/eg/plugin.cc

SRC_MOCHDRS += plugins/eg/plugin.h

######### /plugins/freeverb ########

SRC_HEADERS += plugins/freeverb/allpass_filter.h
SRC_HEADERS += plugins/freeverb/comb_filter.h
SRC_HEADERS += plugins/freeverb/freeverb.h
SRC_HEADERS += plugins/freeverb/reverb_model.h
SRC_HEADERS += plugins/freeverb/plugin.h

SRC_SOURCES += plugins/freeverb/freeverb.cc
SRC_SOURCES += plugins/freeverb/reverb_model.cc
SRC_SOURCES += plugins/freeverb/plugin.cc

SRC_MOCHDRS += plugins/freeverb/plugin.h

################

VERSION_FILE := haruhi/config/version.cc
HEADERS += $(SRC_HEADERS)
SOURCES += $(SRC_SOURCES)
MOCSRCS += $(call mkmocs, $(foreach file, $(SRC_MOCHDRS), $(file)))
OBJECTS += $(call mkobjs, $(SOURCES))
OBJECTS += $(call mkobjs, $(NODEP_SOURCES))
MOCOBJS += $(call mkmocobjs, $(MOCSRCS))
TARGETS += $(distdir)/haruhi
LINKEDS += $(distdir)/haruhi

$(distdir)/haruhi: $(OBJECTS) $(MOCOBJS)

